name: dependabot auto merge

on:
  pull_request_target:
    branches:
      - main

jobs:
  Dependabot-Auto-Merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
